(* generated by OCaml-avro schema compiler *)

module Str_map = Map.Make(String)

let schema = "{\"type\":\"map\",\"values\":\"bytes\"}"

type nonrec t = string Str_map.t

let read (input:Input.t) : t =
  (let readv self = Input.read_string input in
   Input.read_map readv input)

let write (out:Output.t) (self:t) : unit =
  (let writev out self = Output.write_string out self in
           Output.write_map writev out self)
